### ISSUE TITLE
Unhandled error case in strings.Split() in main.go for `sourceWithAtlas.Site`

### ISSUE THREAD

**Issue by nkinkade** [NEU-SNS/revtr-sidecar#7]
We are getting an alert about a container error in an NDT pod on **mlab2-iad03.mlab-oti.measurement-lab.org**. Inspection reveals that it is a CrashLoopBackoff in the `revtr-sidecard` container. The specific error is:

```
2024/01/24 18:48:58 Argument anonymize.ip=none
2024/01/24 18:48:58 Argument loglevel=debug
2024/01/24 18:48:58 Argument logoutput=
2024/01/24 18:48:58 Argument prometheus.port=9998
2024/01/24 18:48:58 WARNING: Not overriding flag -revtr.APIKey="7vg3XfyGIJZL92Ql" with evironment variable REVTR_APIKEY="7vg3XfyGIJZL92Ql"
2024/01/24 18:48:58 Argument revtr.APIKey=7vg3XfyGIJZL92Ql
2024/01/24 18:48:58 Argument revtr.grpcPort=9999
2024/01/24 18:48:58 Argument revtr.hostname=revtr.ccs.neu.edu
2024/01/24 18:48:58 Argument revtr.sampling=100
2024/01/24 18:48:58 Argument tcpinfo.eventsocket=/var/local/tcpinfoeventsocket/tcpevents.sock
time="2024-01-24T18:48:58Z" level=info msg="open  skipped ndt-m7926_1705179035_00000000000DBDB9 2024-01-24 18:48:58.435079101 +0000 UTC &{48914 443 66.198.10.152 35.227.225.103 0 900537}" file=main.go line=116
time="2024-01-24T18:48:58Z" level=info msg="open  skipped ndt-m7926_1705179035_00000000000F007B 2024-01-24 18:48:58.446528926 +0000 UTC &{43108 9999 66.198.10.152 129.10.113.200 0 983163}" file=main.go line=116
panic: runtime error: index out of range [1] with length 1

goroutine 21 [running]:
main.(*handler).ProcessOpenEvents(0xc000124000, {0xb0c2c8, 0xc0000c9b00}, {0x7ffeb2ad2bd6, 0x10}, {0x7ffeb2ad2b77?, 0x0?}, 0x270f, 0x64)
	/go/src/github.com/NEU-SNS/revtr-sidecar/main.go:243 +0x1059
created by main.main
	/go/src/github.com/NEU-SNS/revtr-sidecar/main.go:395 +0x452
```

The error appears to be happening on the following line, which is dependent on the outcome of a `strings.Split()` operation on some variable:

https://github.com/NEU-SNS/revtr-sidecar/blob/main/main.go#L243

This seems to be relying on a particular string format for the variable `sourceWithAtlas.Site`. Is it possible that there is a typo or bad format for a site in `sourcesWithAtlas` for this machine? 

Could someone check to be sure that whatever the source of that string is has the right value. Additionally, it is probably worth adding some error checking to that bit of code just in case string format error happen in the future. Maybe something like:

```
site_parts := strings.Split(sourceWithAtlas.Site, "MLab - ")
site, ok := site_parts[1]
If !ok {
  error()
}
```

**Comment by nkinkade** [comment]
@kvermeul: When you have a moment, is this something you could look into? My assessment may be wrong, in which case perhaps you could point me in the right direction? Thanks!

**Comment by nkinkade** [comment]
We are now seeing the same thing at mlab3-gru02.mlab-oti.measurement-lab.org

**Comment by nkinkade** [comment]
Thank you, @kvermeul. Your new release resolves this issue. The new version is rolling out to production as I write this:

https://github.com/m-lab/k8s-support/releases/tag/v2.43.5
